import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Header from "./../public/Header.png";
import PoweredBy from "./../public/PoweredBy.png";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

const openGraphImage = {
  title: "מערכת הסקרים החכמה של וויפלי",
  cta: "Generated by Wiply",
};

export const metadata: Metadata = {
  title: "מערכת הסקרים החכמה של וויפלי",
  description: "Generated by Wiply",
  openGraph: {
    images: [`/api/og?${new URLSearchParams(openGraphImage)}`],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="he">
      <Head>
        <title>מערכת הסקרים החכמה של וויפלי</title>
        <meta name="description" content="Generated by Wiply" />
      </Head>
      <body className={inter.className}>
        <Script async src="https://www.googletagmanager.com/gtag/js?id=G-C6MWVX5438"></Script>
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-C6MWVX5438');
          `}
        </Script>
        <div className="flex justify-center">
          <main className=" w-screen md:w-2/3 xl:w-1/2 pb-48">
            {children}
          </main>
          <div className="absolute w-full bottom-0 flex flex-col items-center">
            <Image src={PoweredBy} alt="PoweredBy" style={{}} />
          </div>
        </div>
      </body>
    </html>
  );
}
